---
title: "3.1.2.4. Dac diem cua thuoc su dung theo hoat chat"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(ggplot2)
```

```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)

number_end <- str_locate(tonghop$hoatchat, str_extract(tonghop$hoatchat, "_\\d"))[,1]
number_end[which(is.na(number_end))] <- -1
number_start <- rep(1, length(number_end))
hoatchat_ko_hamluong <- tonghop$hoatchat %>% str_sub(number_start, number_end-1)
tonghop$hoatchat_ko_hamluong <- hoatchat_ko_hamluong
```

## So luong hoat chat su dung tu nam 2011 den nam 2017

```{r dac_diem_sl_hoat_chat, echo=FALSE, results='hide',message=FALSE}
sl_thuoc_cung_hoat_chat <- tonghop %>%
  group_by(hoatchat_ko_hamluong) %>%
  summarise(sl_thuoc_cung_hoat_chat = n_distinct(ThuongMai)) %>%
  mutate(value = 1)
```

```{r}
ggplot(sl_thuoc_cung_hoat_chat, aes(x=as.factor(sl_thuoc_cung_hoat_chat), y=value)) +
  geom_bar(stat = "identity") +
  stat_summary(aes(label=round(..y..,2)), fun.y=sum, geom="text", size=5, vjust = -0.5) +
  xlab("Số thuốc có cùng hoạt chất") + 
  ylab("Số hoạt chất")
```

## Cac hoat chat co co so tan duoc su dung nhieu nhat tu nam 2014 - 2018
```{r hoatchat_cs_nhieu, echo=FALSE, results='hide',message=FALSE}
hoatchat_cs_2014_2018 <- tonghop %>%
  group_by(hoatchat_ko_hamluong) %>%
  summarise(cs_thuoc_2014_2018 = sum(xuattrongky_sl, na.rm = TRUE)) %>%
  mutate(cs_thuoc_percent_2014_2018 = cs_thuoc_2014_2018*100/sum(cs_thuoc_2014_2018)) %>%
  top_n(20) %>%
  arrange(desc(cs_thuoc_2014_2018)) %>%
  mutate(index = rep(1:20))

hoatchat_cs_2018 <- tonghop %>%
  filter(nam == 2018) %>%
  group_by(hoatchat_ko_hamluong) %>%
  summarise(cs_thuoc_2018 = sum(xuattrongky_sl, na.rm = TRUE)) %>%
  mutate(cs_thuoc_percent_2018 = cs_thuoc_2018*100/sum(cs_thuoc_2018)) %>%
  filter(hoatchat_ko_hamluong %in% hoatchat_cs_2014_2018$hoatchat_ko_hamluong)

hoatchat_cs <- merge(hoatchat_cs_2014_2018, hoatchat_cs_2018, by="hoatchat_ko_hamluong", all.x = TRUE) %>% 
  arrange(index) %>%
  select(-c(index))
```

```{r}
knitr::kable(hoatchat_cs, format="html", 
             col.names = c("Hoat chat", "Co so thuoc (2014-2018)", "% Co so (2014-2018)",
                           "Co so thuoc (2018)", "% Co so (2018)"))
```


## Chi phi hoat chat su dung tu nam 2014 - 2018
