---
title: "3.1.2.5. Dac diem thuoc tan duoc su dung theo nhom dieu tri"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
```

```{r import_data}
tonghop <- read.csv("./csv/tonghop_processed.csv", stringsAsFactors = FALSE)
tonghop$dem <- rep(1, nrow(tonghop))
tonghop$xuattrongky_sl[which(is.na(tonghop$xuattrongky_sl))] <- 0
tonghop$xuattrongky_thanhtien[which(is.na(tonghop$xuattrongky_thanhtien))] <- 0

# hoatchat_dvt
tonghop$hoatchat_dvt <- paste(tonghop$hoatchat, tonghop$dvt, sep = "_")

```

```{r nhomdieutri_sL_thuoc, echo=FALSE, results='hide',message=FALSE}
nhomdieutri_sl_thuoc <- tonghop %>%
  group_by(nhomdieutri) %>%
  summarise(xuattrongky_sl = sum(xuattrongky_sl, na.rm = TRUE)) %>%
  arrange(desc(xuattrongky_sl)) %>%
  top_n(5)
```

* So luong thuoc duoc su dung theo nhom dieu tri tu nam 2014 den 2018 (5 nhom dieu tri co so luong thuoc su dung cao nhat) * 

```{r nhomdieutri_sl_thuoc}
knitr::kable(nhomdieutri_sl_thuoc, format="html", 
             col.names = c("Nhom DT", "SL thuoc"))
```

```{r nhomdieutri_sl_hoatchat, echo=FALSE, message=FALSE, results='hide'}
number_end <- str_locate(tonghop$hoatchat, str_extract(tonghop$hoatchat, "_\\d"))[,1]
number_end[which(is.na(number_end))] <- -1
number_start <- rep(1, length(number_end))
hoatchat_ko_hamluong <- tonghop$hoatchat %>% str_sub(number_start, number_end-1)
tonghop$hoatchat_ko_hamluong <- hoatchat_ko_hamluong

nhomdieutri_sl_hoatchat <- tonghop %>%
  group_by(nhomdieutri) %>%
  summarise(sl_hoatchat_ko_hamluong = n_distinct(hoatchat_ko_hamluong)) %>%
  arrange(desc(sl_hoatchat_ko_hamluong)) %>%
  top_n(5)
```

* So luong hoat chat duoc su dung theo nhom dieu tri tu nam 2014 den 2018 (5 nhom dieu tri co so luong hoat chat cao nhat) *
```{r tyle_bietduoc}
knitr::kable(nhomdieutri_sl_hoatchat, format="html", 
             col.names = c("Nhom DT", "SL hoat chat"))

```

