---
title: "3.2.3.3. Danh gia tinh chinh xac cua mo hinh"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(plotly)
library(ggplot2)
library(scales)
library(lattice)
library(reshape)
library(forecast)
```

```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)

tt_2019 <- read.csv("/home/hackagon/nckh-holt-winters/csv/tt_2019.csv", stringsAsFactors = FALSE)

danhgia_muasam <- read.csv("/home/hackagon/nckh-holt-winters/csv/danhgia_muasam.csv", stringsAsFactors = FALSE)
danhgia_muasam$coso_muasam_2018 <- as.integer(gsub(danhgia_muasam$coso_muasam_2018, pattern = ",", replacement = ""))

dudoan <- read.csv("/home/hackagon/nckh-holt-winters/csv/dudoan.csv", stringsAsFactors = FALSE)
```

```{r echo=FALSE, results='hide',message=FALSE}
phanloai <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien != 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(
    nhomdieutri = head(nhomdieutri_moi, 1),
    cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE),
    cs_thuoc = sum(xuattrongky_sl, na.rm = TRUE),
    sl_thuoc = n_distinct(ThuongMai)) %>%
  arrange(desc(cp_thuoc)) %>%
  mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
  mutate(phanloai_cp = ifelse(cp_thuoc_percent_tichluy < 67, "A", ifelse(cp_thuoc_percent_tichluy < 80, "B", "C"))) %>%
  arrange(desc(cs_thuoc)) %>%
  mutate(cs_thuoc_percent = cs_thuoc*100/sum(cs_thuoc)) %>%
  mutate(cs_thuoc_percent_tichluy = cumsum(cs_thuoc)*100/sum(cs_thuoc)) %>%
  mutate(phanloai_cs = ifelse(cs_thuoc_percent_tichluy < 67, "A", ifelse(cs_thuoc_percent_tichluy < 80, "B", "C"))) %>%
  filter(phanloai_cs != "C" | phanloai_cp != "C") %>%
  mutate(phanloai = str_c(phanloai_cs, phanloai_cp, sep = "")) %>%
  group_by(nhomdieutri) %>%
  arrange(
    nhomdieutri,
    desc(cs_thuoc_percent)) %>%
  select(c("hoatchat_dvt", "nhomdieutri", "sl_thuoc", "cs_thuoc", "cs_thuoc_percent", "cp_thuoc", "cp_thuoc_percent", "phanloai"))

phanloai$phanloai[which(phanloai$phanloai  == "CA")] <- "AC"
phanloai$phanloai[which(phanloai$phanloai  == "CB")] <- "BC"
phanloai$phanloai[which(phanloai$phanloai  == "BA")] <- "AB"

phanloai <- phanloai %>%
  arrange(desc(cs_thuoc))
```

```{r bietduoc, echo=FALSE, results='hide',message=FALSE}
vt_hoatchat <- c()
vt_coso_sd_tt_6th_2019 <- c()
vt_coso_muasam_6th_2019 <- c()
vt_coso_mohinh_6th_2019 <- c()

i <- 1
while(i <= nrow(phanloai)){
  hoatchat <- phanloai$hoatchat_dvt[i]
  index <- which(tonghop$hoatchat_dvt == hoatchat)
  nhomBD <- unique(tonghop$nhomBD[index])
  if(length(nhomBD) == 1 && unique(nhomBD) == 1){
    # hoat chat
    vt_hoatchat <- c(vt_hoatchat, hoatchat)
    
    # coso sd thuc te
    tt_2019_6th <- tt_2019 %>% filter(thang %in% c(1,2,3,4,5,6))
    thuoc_index <- which(tt_2019_6th$hoatchat_dvt == hoatchat) 
    coso_sd_tt_6th_2019 <- sum(tt_2019_6th$xuattrongky_sl[thuoc_index])
    vt_coso_sd_tt_6th_2019 <- c(vt_coso_sd_tt_6th_2019, coso_sd_tt_6th_2019)
    
    # coso mua sam
    thuoc_index_2 <- which(danhgia_muasam$hoatchat == hoatchat)
    coso_muasam_12th <- danhgia_muasam$coso_muasam_2018[thuoc_index_2]
    df_coso_sd_6thcuoi_2018 <- tonghop %>% 
      filter(hoatchat_dvt == !!hoatchat) %>%
      filter(nam == 2018) %>%
      filter(thang %in% c(7,8,9,10,11,12)) %>%
      summarise(tong = sum(xuattrongky_sl))
    coso_sd_6thcuoi_2018 <- df_coso_sd_6thcuoi_2018$tong
    coso_muasam_6th_2019 <- coso_muasam_12th - coso_sd_6thcuoi_2018
    vt_coso_muasam_6th_2019 <- c(vt_coso_muasam_6th_2019, coso_muasam_6th_2019)
    
    # coso mo hinh
    dudoan_index <- which(dudoan$vt_hoatchat == hoatchat)
    vt_coso_mohinh_6th_2019 <-c(vt_coso_mohinh_6th_2019, dudoan$vt_dudoan_2019_6thdau[dudoan_index])
  }
  i <- i + 1
}

danhgia_bietduoc <- data.frame(vt_hoatchat, vt_coso_sd_tt_6th_2019, vt_coso_muasam_6th_2019, vt_coso_mohinh_6th_2019)

danhgia_bietduoc$chenhlech_musam_thucte <- (danhgia_bietduoc$vt_coso_muasam_6th_2019 - danhgia_bietduoc$vt_coso_sd_tt_6th_2019)*100/danhgia_bietduoc$vt_coso_sd_tt_6th_2019
danhgia_bietduoc$chenhlech_mohinh_thucte <- (danhgia_bietduoc$vt_coso_mohinh_6th_2019 - danhgia_bietduoc$vt_coso_sd_tt_6th_2019)*100/danhgia_bietduoc$vt_coso_sd_tt_6th_2019
```

## Bang danh gia biet duoc
```{r}
knitr::kable(danhgia_bietduoc, format="html", 
            col.names = c("Hoat chat", "Co so su dung thuc te", "Co so mua sam", "Co so du doan", "% Chenh lech giua co so mua sam va thuc te", "% Chenh lech giua co so du doan va thuc te"))
```

```{r generic, echo=FALSE, results='hide',message=FALSE}
vt_hoatchat <- c()
vt_coso_sd_tt_9th_2019 <- c()
vt_coso_muasam_9th_2019 <- c()
vt_coso_mohinh_9th_2019 <- c()

i <- 1
while(i <= nrow(phanloai)){
  hoatchat <- phanloai$hoatchat_dvt[i]
  index <- which(tonghop$hoatchat_dvt == hoatchat)
  nhomBD <- unique(tonghop$nhomBD[index])
  if(length(nhomBD) == 1 && unique(nhomBD) == 2){
    # hoat chat
    vt_hoatchat <- c(vt_hoatchat, hoatchat)
    
    # coso sd thuc te
    thuoc_index <- which(tt_2019$hoatchat_dvt == hoatchat) 
    coso_sd_tt_9th_2019 <- sum(tt_2019$xuattrongky_sl[thuoc_index])
    vt_coso_sd_tt_9th_2019 <- c(vt_coso_sd_tt_9th_2019, coso_sd_tt_9th_2019)
    
    # coso mua sam
    thuoc_index_2 <- which(danhgia_muasam$hoatchat == hoatchat)
    coso_muasam_12th <- danhgia_muasam$coso_muasam_2018[thuoc_index_2]
    df_coso_sd_3thcuoi_2018 <- tonghop %>% 
      filter(hoatchat_dvt == !!hoatchat) %>%
      filter(nam == 2018) %>%
      filter(thang %in% c(10,11,12)) %>%
      summarise(tong = sum(xuattrongky_sl))
    coso_sd_3thcuoi_2018 <- df_coso_sd_3thcuoi_2018$tong
    coso_muasam_9th_2019 <- coso_muasam_12th - coso_sd_3thcuoi_2018
    vt_coso_muasam_9th_2019 <- c(vt_coso_muasam_9th_2019, coso_muasam_9th_2019)
    
    # coso mo hinh
    dudoan_index <- which(dudoan$vt_hoatchat == hoatchat)
    vt_coso_mohinh_9th_2019 <-c(vt_coso_mohinh_9th_2019, dudoan$vt_dudoan_2019_9thdau[dudoan_index])
  }
  i <- i + 1
}

danhgia_generic <- data.frame(vt_hoatchat, vt_coso_sd_tt_9th_2019, vt_coso_muasam_9th_2019, vt_coso_mohinh_9th_2019)

danhgia_generic$chenhlech_musam_thucte <- (danhgia_generic$vt_coso_muasam_9th_2019 - danhgia_generic$vt_coso_sd_tt_9th_2019)*100/danhgia_generic$vt_coso_sd_tt_9th_2019
danhgia_generic$chenhlech_mohinh_thucte <- (danhgia_generic$vt_coso_mohinh_9th_2019 - danhgia_generic$vt_coso_sd_tt_9th_2019)*100/danhgia_generic$vt_coso_sd_tt_9th_2019
```

## Bang danh gia Generic
```{r}
knitr::kable(danhgia_generic, format="html", 
            col.names = c("Hoat chat", "Co so su dung thuc te", "Co so mua sam", "Co so du doan", "% Chenh lech giua co so mua sam va thuc te", "% Chenh lech giua co so du doan va thuc te"))
```