---
title: "3.2.1.2. Phan loai hoat chat theo chi phi su dung"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(plotly)
library(ggplot2)
```


```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)
```

# Phan loai hoat chat theo chi phi su dung nam 2018

## BANG PHUC LUC: Phan loai hoat chat dua theo chi phi su dung nam 2018
#### (Chi in 20 rows tuong trung, khi lam phu luc se xuat ra day dau)
#### Co 1 so row co chi phi su dung = 0 ==> loai bo
```{r phanloai_cp_thuoc, echo=FALSE, results='hide',message=FALSE}
phanloai_cp_thuoc <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien == 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE)) %>%
  arrange(desc(cp_thuoc)) %>%
  mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
  head(20)
```
```{r phanloai_cp_thuoc_table}
knitr::kable(phanloai_cp_thuoc, format="html", 
             col.names = c("Hoat chat", "CP thuoc", "% CP thuoc", "% tich luy"))
```

## BANG: Phan loai hoat chat dua theo co so su dung nam 2018
```{r phanloai_cp_thuoc_ABC, echo=FALSE, results='hide',message=FALSE}
phanloai_cp_thuoc <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien != 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE),
            sl_hoatchat = n_distinct(hoatchat_dvt)) %>%
  arrange(desc(cp_thuoc)) %>%
  mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
  mutate(phanloai_cp = ifelse(cp_thuoc_percent_tichluy < 67, "A", ifelse(cp_thuoc_percent_tichluy < 80, "B", "c"))) %>%
  group_by(phanloai_cp) %>%
  summarise(sl_hoatchat = sum(sl_hoatchat), cp_thuoc = sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
  mutate(phanloai_cp = c("A", "B", "C"))
```

```{r phanloai_cp_thuoc_ABC_table}
knitr::kable(phanloai_cp_thuoc, format="html", 
             col.names = c("Phan loai", "SL hoat chat", "Co so thuoc", "% Co so thuoc", "% tich luy"))
```