---
title: 3.2.2.1. Xac dinh xu huong su dung giai doan 2014-2018 cua cac hoat chat duoc
  su dung nhieu trong nam 2018
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(plotly)
library(ggplot2)
library(scales)
```

```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)
```

```{r phanloai, echo=FALSE, results='hide',message=FALSE}
phanloai <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien != 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(
    nhomdieutri = head(nhomdieutri_moi, 1),
    cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE),
    cs_thuoc = sum(xuattrongky_sl, na.rm = TRUE),
    sl_thuoc = n_distinct(ThuongMai)) %>%
    arrange(desc(cp_thuoc)) %>%
    mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
    mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
    mutate(phanloai_cp = ifelse(cp_thuoc_percent_tichluy < 67, "A", ifelse(cp_thuoc_percent_tichluy < 80, "B", "C"))) %>%
    arrange(desc(cs_thuoc)) %>%
    mutate(cs_thuoc_percent = cs_thuoc*100/sum(cs_thuoc)) %>%
    mutate(cs_thuoc_percent_tichluy = cumsum(cs_thuoc)*100/sum(cs_thuoc)) %>%
    mutate(phanloai_cs = ifelse(cs_thuoc_percent_tichluy < 67, "A", ifelse(cs_thuoc_percent_tichluy < 80, "B", "C"))) %>%
    filter(phanloai_cs != "C" | phanloai_cp != "C") %>%
    mutate(phanloai = str_c(phanloai_cs, phanloai_cp, sep = "")) %>%
  group_by(nhomdieutri) %>%
  arrange(
    nhomdieutri,
    desc(cs_thuoc_percent)) %>%
  select(c("hoatchat_dvt", "nhomdieutri", "sl_thuoc", "cs_thuoc", "cs_thuoc_percent", "cp_thuoc", "cp_thuoc_percent", "phanloai"))

phanloai$phanloai[which(phanloai$phanloai  == "CA")] <- "AC"
phanloai$phanloai[which(phanloai$phanloai  == "CB")] <- "BC"
phanloai$phanloai[which(phanloai$phanloai  == "BA")] <- "AB"

phanloai %>%
  arrange(phanloai)
```

```{r utils_function, echo=FALSE, results='hide',message=FALSE}
lay_co_so_thuoc_theo_thoi_gian <- function(hoatchat){
  tonghop %>%
    filter(hoatchat_dvt == !!hoatchat) %>%
    select(c("xuattrongky_sl", "nam", "thang")) %>%
    mutate(date = as.Date(str_c(nam, thang, "01", sep = "-"))) %>%
    group_by(date) %>%
    summarise(coso = sum(xuattrongky_sl)) %>%
    arrange(date)  
}

bieudo_coso_phanloai <- function(pl){
  vt_hoatchat <- phanloai$hoatchat_dvt[which(phanloai$phanloai == pl)]
  df <- data.frame()
  i <- 1
  while(i <= length(vt_hoatchat)){
    df_hoatchat <- lay_co_so_thuoc_theo_thoi_gian(vt_hoatchat[i]) %>%
      mutate(hoatchat = vt_hoatchat[i])
    df <- rbind(df, df_hoatchat)
    i <- i + 1
  }
  df %>%
    ggplot(aes(x = date, y = coso)) + 
    geom_line() + 
    facet_grid(hoatchat ~ ., scales = "free_y") + theme(legend.position = "none") +
    geom_point() +
    xlab("Thời gian") + 
    scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
    ylab("Cơ số sử dụng") + 
    theme_minimal() +
    ggtitle(label = str_c("Phan loai ", pl))
}
```

### Bieu do (dua vao bai viet)

```{r bieudo}
bieudo_coso_phanloai("AA")
bieudo_coso_phanloai("AB")
bieudo_coso_phanloai("AC")
bieudo_coso_phanloai("BB")
bieudo_coso_phanloai("BC")
```

### Bang so lieu thong ke (khong dua vao bai viet)

```{r bang_thongke, echo=FALSE, results='hide',message=FALSE}
vt_hoatchat <- phanloai$hoatchat_dvt[which(phanloai$phanloai != "CC")]
df <- data.frame()
i <- 1
while(i <= length(vt_hoatchat)){
  df_temp <- lay_co_so_thuoc_theo_thoi_gian(vt_hoatchat[i])
  names(df_temp)[2] <- vt_hoatchat[i]
  if(nrow(df) == 0){
    df <- df_temp 
  } else {
    df <- merge(df, df_temp, by.x = "date", by.y = "date", all.x = TRUE)
  }
  
  i <- i + 1
}
df
```

```{r kq_bang_thong_ke}
knitr::kable(df, format="html", 
             col.names = names(df))
```
