---
title: "3.2.2.4. Danh gia tinh hinh mua sam"
output:
  md_document:
    variant: markdown_github
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(plotly)
library(ggplot2)
library(scales)
library(lattice)
```

```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)
```

```{r phanloai, echo=FALSE, results='hide',message=FALSE}
phanloai <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien != 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(
    nhomdieutri = head(nhomdieutri_moi, 1),
    cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE),
    cs_thuoc = sum(xuattrongky_sl, na.rm = TRUE),
    sl_thuoc = n_distinct(ThuongMai)) %>%
    arrange(desc(cp_thuoc)) %>%
    mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
    mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
    mutate(phanloai_cp = ifelse(cp_thuoc_percent_tichluy < 67, "A", ifelse(cp_thuoc_percent_tichluy < 80, "B", "C"))) %>%
    arrange(desc(cs_thuoc)) %>%
    mutate(cs_thuoc_percent = cs_thuoc*100/sum(cs_thuoc)) %>%
    mutate(cs_thuoc_percent_tichluy = cumsum(cs_thuoc)*100/sum(cs_thuoc)) %>%
    mutate(phanloai_cs = ifelse(cs_thuoc_percent_tichluy < 67, "A", ifelse(cs_thuoc_percent_tichluy < 80, "B", "C"))) %>%
    filter(phanloai_cs != "C" | phanloai_cp != "C") %>%
    mutate(phanloai = str_c(phanloai_cs, phanloai_cp, sep = "")) %>%
  group_by(nhomdieutri) %>%
  arrange(
    nhomdieutri,
    desc(cs_thuoc_percent)) %>%
  select(c("hoatchat_dvt", "nhomdieutri", "sl_thuoc", "cs_thuoc", "cs_thuoc_percent", "cp_thuoc", "cp_thuoc_percent", "phanloai"))

phanloai$phanloai[which(phanloai$phanloai  == "CA")] <- "AC"
phanloai$phanloai[which(phanloai$phanloai  == "CB")] <- "BC"
phanloai$phanloai[which(phanloai$phanloai  == "BA")] <- "AB"

phanloai <- phanloai %>%
  arrange(desc(cs_thuoc))
```

```{r echo=FALSE, results='hide',message=FALSE}
vt_coso_sudung_2018 <- c()
vt_coso_muasam_2018 <- c()
vt_coso_duoi <- c()
vt_coso_tren <- c()
vt_mean <- c()
vt_hc <- c()
df <- data.frame()
for(hc in phanloai$hoatchat_dvt){
  coso_nam <- tonghop %>% 
    filter(hoatchat_dvt == hc) %>%
    select(c("xuattrongky_sl", "nam")) %>%
    group_by(nam) %>%
    summarise(coso = sum(xuattrongky_sl))
  
  vt_hc <- c(vt_hc, hc)
  
  coso_2018 <- coso_nam[which(coso_nam$nam == 2018),]$coso
  vt_coso_sudung_2018 <- c(vt_coso_sudung_2018, coso_2018)
  vt_coso_muasam_2018 <- c(vt_coso_muasam_2018, "NA")
  
  sd <- qt(0.975,df=4)*sd(coso_nam$coso)
  mean <- mean(coso_nam$coso)
  low <- mean - sd/sqrt(5)
  high <- mean + sd/sqrt(5)
  vt_mean <- c(vt_mean, mean)
  vt_coso_duoi <- c(vt_coso_duoi, low)
  vt_coso_tren <- c(vt_coso_tren, high)
}

df <- data.frame(vt_hc, vt_coso_sudung_2018, vt_coso_muasam_2018, vt_coso_duoi, vt_coso_tren)
```

```{r}
knitr::kable(df, format="html", 
             col.names = c("Hoat chat", "Co so sd 2018", "Co so mua sam 2018", "gioi han duoi", "gioi han tren"))
```


