---
title: "3.2.3.2.Du_lieu_co_so_du_bao_2019_2020"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(plotly)
library(ggplot2)
library(scales)
library(lattice)
library(reshape)
library(forecast)
```

```{r import_data, echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("/home/hackagon/nckh-holt-winters/csv/tonghop_processed.csv", stringsAsFactors = FALSE)
```

```{r echo=FALSE, results='hide',message=FALSE}
phanloai <- tonghop %>%
  filter(nam == 2018) %>%
  filter(xuattrongky_thanhtien != 0) %>%
  group_by(hoatchat_dvt) %>%
  summarise(
    nhomdieutri = head(nhomdieutri_moi, 1),
    cp_thuoc = sum(xuattrongky_thanhtien, na.rm = TRUE),
    cs_thuoc = sum(xuattrongky_sl, na.rm = TRUE),
    sl_thuoc = n_distinct(ThuongMai)) %>%
  arrange(desc(cp_thuoc)) %>%
  mutate(cp_thuoc_percent = cp_thuoc*100/sum(cp_thuoc)) %>%
  mutate(cp_thuoc_percent_tichluy = cumsum(cp_thuoc)*100/sum(cp_thuoc)) %>%
  mutate(phanloai_cp = ifelse(cp_thuoc_percent_tichluy < 67, "A", ifelse(cp_thuoc_percent_tichluy < 80, "B", "C"))) %>%
  arrange(desc(cs_thuoc)) %>%
  mutate(cs_thuoc_percent = cs_thuoc*100/sum(cs_thuoc)) %>%
  mutate(cs_thuoc_percent_tichluy = cumsum(cs_thuoc)*100/sum(cs_thuoc)) %>%
  mutate(phanloai_cs = ifelse(cs_thuoc_percent_tichluy < 67, "A", ifelse(cs_thuoc_percent_tichluy < 80, "B", "C"))) %>%
  filter(phanloai_cs != "C" | phanloai_cp != "C") %>%
  mutate(phanloai = str_c(phanloai_cs, phanloai_cp, sep = "")) %>%
  group_by(nhomdieutri) %>%
  arrange(
    nhomdieutri,
    desc(cs_thuoc_percent)) %>%
  select(c("hoatchat_dvt", "nhomdieutri", "sl_thuoc", "cs_thuoc", "cs_thuoc_percent", "cp_thuoc", "cp_thuoc_percent", "phanloai"))

phanloai$phanloai[which(phanloai$phanloai  == "CA")] <- "AC"
phanloai$phanloai[which(phanloai$phanloai  == "CB")] <- "BC"
phanloai$phanloai[which(phanloai$phanloai  == "BA")] <- "AB"

phanloai <- phanloai %>%
  arrange(desc(cs_thuoc))
```

```{r utils_function, echo=FALSE, results='hide',message=FALSE}
lay_co_so_thuoc_theo_thoi_gian <- function(hoatchat){
  thuoc <- tonghop %>%
    filter(hoatchat_dvt == !!hoatchat) %>%
    select(c("xuattrongky_sl", "nam", "thang")) %>%
    mutate(date = as.Date(str_c(nam, thang, "01", sep = "-"))) %>%
    group_by(date) %>%
    summarise(coso = sum(xuattrongky_sl)) %>%
    arrange(date) 
  
  vt_nam <- c(rep(2014, 12), rep(2015, 12), rep(2016, 12), rep(2017, 12), rep(2018, 12))
  vt_thang <- c(rep(c(1:12), 5))
  vt_ngay <- c(rep(1, 60))
  vt_date <- as.Date((str_c(vt_nam, vt_thang, vt_ngay, sep="-")))
  
  i <- 1
  while(i <= length(vt_date)){
    index <- which(thuoc$date == vt_date[i])
    if(length(index) == 0){
      n_index <- nrow(thuoc) + 1
      thuoc[n_index, 1] <- vt_date[i]
      thuoc[n_index, 2] <- 0
    }
    i <- i + 1
  }
  
  thuoc %>% 
    arrange(date) %>%
    mutate(nam = str_sub(date, 1, 4))
}

coso_tb_dudoan <- function(pl){
  vt_hoatchat <- phanloai$hoatchat_dvt[which(phanloai$phanloai == pl)]
  #vt_hoatchat <- vt_hoatchat[which(vt_hoatchat != "bortezomib_1mg_lo")]
  sl_hoatchat <- length(vt_hoatchat)

  vt_coso_tb_2014_2018 <- c()
  vt_dudoan_2019 <- c()
  vt_dudoan_2020 <- c()
  i <- 1
  while(i <= sl_hoatchat){
    df_hoatchat <- lay_co_so_thuoc_theo_thoi_gian(vt_hoatchat[i]) %>%
      mutate(hoatchat = vt_hoatchat[i])
    
    coso_thuoc <- as.ts(df_hoatchat$coso)
    coso_date <- ts(coso_thuoc, start=c(2014, 1), frequency = 12)
    hw <- HoltWinters(coso_date)
    fit <- forecast:::forecast.HoltWinters(hw)
    
    dudoan_2019 <- sum(fit$mean[1:12])
    vt_dudoan_2019 <- c(vt_dudoan_2019, dudoan_2019)
    
    dudoan_2020 <- sum(fit$mean[13:24])
    vt_dudoan_2020 <- c(vt_dudoan_2020, dudoan_2020)
    
    coso_tb_2014_2018 <- sum(coso_thuoc)/5 # 5 years
    vt_coso_tb_2014_2018 <- c(vt_coso_tb_2014_2018, coso_tb_2014_2018)
    i <- i + 1
  }
  
  data.frame(vt_hoatchat, vt_coso_tb_2014_2018, vt_dudoan_2019, vt_dudoan_2020)
}
```

```{r echo=FALSE, results='hide',message=FALSE}
dudoan_AA <- coso_tb_dudoan("AA") %>% mutate(phanloai = "AA")
dudoan_AB <- coso_tb_dudoan("AB") %>% mutate(phanloai = "AB")
dudoan_AC <- coso_tb_dudoan("AC") %>% mutate(phanloai = "AC")
dudoan_BB <- coso_tb_dudoan("BB") %>% mutate(phanloai = "BB")
dudoan_BC <- coso_tb_dudoan("BC") %>% mutate(phanloai = "BC")

dudoan <- rbind(dudoan_AA, dudoan_AB, dudoan_AC, dudoan_BB, dudoan_BC)
```

```{r}
knitr::kable(dudoan, format="html", 
            col.names = c("Hoat chat", "Co so TB 2014-2018", "Du doan 2019", "Du doan 2020", "phanloai"))
```