---
title: "Dac diem cac thuoc su dung theo biet duoc va generic"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, results='hide',message=FALSE}
tonghop <- read.csv("./csv/tonghop_processed.csv", stringsAsFactors = FALSE)
tonghop$dem <- rep(1, nrow(tonghop))
tonghop$xuattrongky_sl[which(is.na(tonghop$xuattrongky_sl))] <- 0
tonghop$xuattrongky_thanhtien[which(is.na(tonghop$xuattrongky_thanhtien))] <- 0

# hoatchat_dvt
tonghop$hoatchat_dvt <- paste(tonghop$hoatchat, tonghop$dvt, sep = "_")
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "albumin_200_lo")] <- "albumin_200_chai"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "clinoleic_100_chai")] <- "clinoleic_100_tui"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "deferasirox_125_lo")] <- "deferasirox_125_vien"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "metronidazol_500_lo")] <- "metronidazol_500_chai"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "midazolam_5mg_1ml_vien")] <- "midazolam_5mg_1ml_lo"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "pegfilgrastim_6mg_0,6ml_lo")] <- "pegfilgrastim_6mg_0,6ml_bom_tiem"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "paracetamol_1000mg_lo")] <- "paracetamol_1000mg_chai"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "ciclosporin_100mg_ml_vien")] <- "ciclosporin_100mg_ml_chai"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "ciclosporin_25mg_ml_vien")] <- "ciclosporin_25mg_ml_chai"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "vitamin_c_500_lo")] <- "vitamin_c_500_vien"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "azithromycin_200mg_5ml_chai")] <- "azithromycin_200mg_5ml_lo"
tonghop$hoatchat_dvt[which(tonghop$hoatchat_dvt == "zoledronic_acid_4mg_chai")] <- "zoledronic_acid_4mg_lo"


# biet duoc
bietduoc_index <- which(tonghop$nhomBD == 1) 
bietduoc_df <- tonghop[bietduoc_index, ]
bietduoc_aggregate_df <- aggregate(xuattrongky_sl ~ hoatchat_dvt, bietduoc_df,FUN = sum)
bietduoc_aggregate_df$xuattrongky_thanhtien <- aggregate(xuattrongky_thanhtien ~ hoatchat_dvt, bietduoc_df,FUN = sum)$xuattrongky_thanhtien
bietduoc_sl_thuoc <- nrow(bietduoc_aggregate_df)
bietduoc_coso_thuoc_sd <- sum(bietduoc_aggregate_df$xuattrongky_sl)
bietduoc_cp <- sum(bietduoc_aggregate_df$xuattrongky_thanhtien)

# generic
generic_index <- which(tonghop$nhomBD == 2) 
generic_df <- tonghop[generic_index, ]
generic_aggregate_df <- aggregate(xuattrongky_sl ~ hoatchat_dvt, generic_df,FUN = sum)
generic_aggregate_df$xuattrongky_thanhtien <- aggregate(xuattrongky_thanhtien ~ hoatchat_dvt, generic_df,FUN = sum)$xuattrongky_thanhtien
generic_sl_thuoc <- nrow(generic_aggregate_df)
generic_coso_thuoc_sd <- sum(generic_aggregate_df$xuattrongky_sl)
generic_cp <- sum(generic_aggregate_df$xuattrongky_thanhtien)

# tong so luong thuoc theo bietduoc/generic
tong_sl_thuoc <- bietduoc_sl_thuoc + generic_sl_thuoc
tong_coso_thuoc_sd <- bietduoc_coso_thuoc_sd + generic_coso_thuoc_sd
tong_cp <- bietduoc_cp + generic_cp

bietduoc_phantram <- bietduoc_sl_thuoc / tong_sl_thuoc
generic_phantram <- generic_sl_thuoc / tong_sl_thuoc
bietduoc_coso_sd_phantram <- bietduoc_coso_thuoc_sd / tong_coso_thuoc_sd
generic_coso_sd_phantram <- generic_coso_thuoc_sd / tong_coso_thuoc_sd
bietduoc_cp_phantram <- bietduoc_cp / tong_cp
generic_cp_phantram <- generic_cp / tong_cp

# generate bietduoc_generic_df
bietduoc_generic_df <- data.frame(matrix(ncol = 0, nrow = 2))
bietduoc_generic_df$phan_loai <- c("Biet duoc", "Generic")
bietduoc_generic_df$sl_thuoc <- c(bietduoc_sl_thuoc, generic_sl_thuoc)
bietduoc_generic_df$thuoc_phantram <- c(bietduoc_phantram, generic_phantram)
bietduoc_generic_df$coso_thuoc_sd <- c(bietduoc_coso_thuoc_sd, generic_coso_thuoc_sd)
bietduoc_generic_df$coso_thuoc_sd_phantram <- c(bietduoc_coso_sd_phantram, generic_coso_sd_phantram)
bietduoc_generic_df$cp_thuoc <- c(bietduoc_cp, generic_cp)
bietduoc_generic_df$cp_thuoc_phantram <- c(bietduoc_cp_phantram, generic_cp_phantram)
```

**3.1.1 Dac diem cac thuoc su dung theo phan loai thuoc biet duoc va generic tai benh vien TMHH giai doan 2014 - 2018**

* Mo ta dac diem cua cac thuoc su dung theo phan loai thuoc biet duoc va generic trong 5 nam tu 2014 - 2018

```{r bietduoc_generic}
knitr::kable(bietduoc_generic_df, format="html", 
             col.names = c("Phan loai", "SL thuoc", "% thuoc", "Co so", "% co so", "Chi phi", "% chi phi"))
```

```{r echo=FALSE, results='hide',message=FALSE}
bietduoc_nam <- aggregate(x=list(
  coso = as.numeric(bietduoc_df$xuattrongky_sl),
  chiphi = as.numeric(bietduoc_df$xuattrongky_thanhtien)
  ), by=list(nam=bietduoc_df$nam), FUN=sum)

bietduoc_nam$soluong <- c(
  length(unique(bietduoc_df[which(bietduoc_df$nam == 2014), ]$hoatchat)),
  length(unique(bietduoc_df[which(bietduoc_df$nam == 2015), ]$hoatchat)),
  length(unique(bietduoc_df[which(bietduoc_df$nam == 2016), ]$hoatchat)),
  length(unique(bietduoc_df[which(bietduoc_df$nam == 2017), ]$hoatchat)),
  length(unique(bietduoc_df[which(bietduoc_df$nam == 2018), ]$hoatchat))
)
```

* Mo ta tang giam biet duoc qua cac nam

```{r tyle_bietduoc}
knitr::kable(bietduoc_nam, format="html", 
             col.names = c("nam", "co so", "chi phi", "so luong"))

```

```{r echo=FALSE, results='hide',message=FALSE}
generic_nam <- aggregate(x=list(
  coso = as.numeric(generic_df$xuattrongky_sl),
  chiphi = as.numeric(generic_df$xuattrongky_thanhtien)
  ), by=list(nam=generic_df$nam), FUN=sum)

generic_nam$soluong <- c(
  length(unique(generic_df[which(generic_df$nam == 2014), ]$hoatchat)),
  length(unique(generic_df[which(generic_df$nam == 2015), ]$hoatchat)),
  length(unique(generic_df[which(generic_df$nam == 2016), ]$hoatchat)),
  length(unique(generic_df[which(generic_df$nam == 2017), ]$hoatchat)),
  length(unique(generic_df[which(generic_df$nam == 2018), ]$hoatchat))
)
```

* Mo ta tang giam generic qua cac nam

```{r tyle_generic}
knitr::kable(generic_nam, format="html", 
             col.names = c("nam", "co so", "chi phi", "so luong"))
```


### GHI CHU: mot hoat chat co the co nhieu ten thuong mai nen 335 + 107 > 409 (tong hoatchat_dvt) la binh thuong


```{r unit test}
# unique_hoatchat_dvt <- unique(tonghop$hoatchat_dvt)
# i <- 1
# while(i <= length(unique_hoatchat_dvt)){
#   index <- which(tonghop$hoatchat_dvt == unique_hoatchat_dvt[i])
#   unique <- unique(tonghop$nhomBD[index])
#   if(length(unique) > 1){
#   print(i)
#   }
#   i <- i + 1
# }
```